### ISSUE TITLE
Thanks;

### ISSUE THREAD

**Issue by dekken201** [adolfintel/tetrispuzzlesolver-html5#1]
Hey man, not really and issue, but I didn't find any way to write to you besides here.
Thanks for this cool algorithm, really helped me out. Can you give me a quick rundown on to how it works? I'd like to replicate it to test my skills.
Thanks again!

**Comment by adolfintel** [comment]
The basic idea is a recursive algorithm that tries all possible combinations. Here's how it works:

1. You have a board of WxH cells, initially empty (0)
2. You have a queue of pieces that you want to add to the board (each has a type I,O,T,J,L,S,Z and a number >=1)
3. The algorithm first does some preliminary checks: the puzzle cannot be solved if the number of cells in the board is not a multiple of 4; also, the number of pieces*4 must be equal to the number of cells. If these 2 conditions are true, the puzzle MAY have a solution and we can proceed
4. If the queue of pieces is empty, the puzzle is solved and we return true
5. Scan the board, find all groups of contiguous empty cells. If any of the groups has a number of cells that is not multiple of 4, we made a mistake somewhere so we return false
6. Extract the piece in front of the queue
7. Iteratively, go through all the positions where this piece could fit: for each of them, place the piece on the board (set the cells to the piece's id) and repeat recursively from step 4. If the recursion returns true, return true; otherwise remove the piece from the board (set the cells back to 0) and look for another place where it fits
8. If the piece didn't fit anywhere, put it back in the queue and return false

Note that this is not the only solution for this problem, as it can be represented as a case of Knuth's Algorithm X, and there are heuristic algorithms that can solve it (but with no guarantee of finding a solution).
